name: TestRun

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build app
        run: npm run build